export const translations = {
  ar: {
    chooseLanguage: "اختار اللغة",
    next: "التالي",
    skip: "تخطي",
    getStarted: "انطلق",
    CreateAcc: "انشاء حساب",
    Search: "بحث",
    searchDrivers: "ابحث عن السائقين",
    onboarding: [
      {
        title: "سافر بذكاء، وفر وقتك مع وصلني!",
        description: "ابحث عن اشخاص يشاركون نفس وجهتك واستمتع برحلات مريحة بتكاليف أقل."
      },
      {
        title: "كن سائقًا وساعد الآخرين!",
        description: "إذا كان لديك مقعد فارغ، لا تذهب وحدك! شارك رحلتك وساعد الناس مع إمكانية تقليل تكاليف التنقل."
      },
      {
        title: "جاهز للانطلاق؟",
        description: 'ابدأ الآن وانضم إلى مجتمع التنقل الذكي! اضغط على "انطلق" وسجل حسابك لتجد رحلتك الأولى!'
      }
    ],
    signUp: "انشاء حساب جديد",
    signIn: "تسجيل الدخول",
    signUpButton: "تسجيل",
    phoneNumber: "رقم الهاتف",
    fullName: "الاسم ",
    enterYourName: "اكتب اسمك",
    email: "البريد الإلكتروني",
    password: "كلمة السر",
    gender: "الجنس",
    selectGender: "اختر الجنس",
    workIndustry: "مجال العمل",
    selectIndustry: "اختر مجال العمل",
    agreeToTerms: "أوافق على الشروط والأحكام",
    cancel: "إلغاء",
    signUpHint: "اضغط لإكمال التسجيل",
    enterPhone: "أدخل رقم الهاتف",
    enterEmail: "أدخل البريد الإلكتروني",
    enterPassword: "أدخل كلمة المرور",
    enterConfirmPassword: "أدخل تأكيد كلمة المرور",
    enterVerificationCode: "أدخل رمز التحقق",
    verifyEmailHint: "تحقق من بريدك الإلكتروني",
    navigateToHomeHint: "انتقل إلى الصفحة الرئيسية",
    loading: "جاري التحميل...",
    genders: ['ذكر', 'أنثى'],
    industries: [
      'طالب',
      'موظف',
      'أعمال حرة',
      'مهندس',
      'طبيب',
      'معلم',
      'محاسب',
      'مطور برمجيات',
      'تاجر',
      'عامل في الصحة',
    ],
    other: "اخرى",
    login: "تسجيل الدخول",
    forgotPassword: "نسيت كلمة السر؟",
    noAccount: "لا يوجد حساب؟",
    agreeToTermsAlert: "يرجى الموافقة على الشروط والأحكام",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    logIn: "تسجيل الدخول",
    verificationSent: "تم إرسال رمز التحقق إلى",
    code: "رمز التحقق",
    verifyEmail: "تحقق من البريد الإلكتروني",
    verified: "تم التحقق",
    verificationSuccess: "لقد تم التحقق من حسابك بنجاح.",
    browseHome: "تصفح الصفحة الرئيسية",
    error: "خطأ",
    fillAllFields: "يرجى ملء جميع الحقول.",
    verificationFailed: "فشل التحقق. يرجى المحاولة مرة أخرى.",
    SendVCode: "لقد أرسلنا رمز التحقق إلى",
    Verification: "تحقق",
    Code: "رمز التحقق",
    VerifyEmail: "تحقق من البريد الإلكتروني",
    signInFailed: "فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.",
    welcome: "مرحبا بك!",
    forgotPasswordDescription: "أدخل بريدك الإلكتروني لإرسال رابط إعادة تعيين كلمة المرور.",
    sendResetLink: "إرسال الرابط",
    backToSignIn: "العودة إلى تسجيل الدخول",
    fillEmailField: "يرجى إدخال البريد الإلكتروني.",
    resetPasswordLinkSent: "تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.",
    success: "نجاح",
    resetPassword: "إعادة تعيين كلمة المرور",
    resetPasswordDescription: "أدخل رمز التحقق الذي تلقيته عبر البريد الإلكتروني وكلمة المرور الجديدة.",
    verificationCode: "رمز التحقق",
    newPassword: "كلمة المرور الجديدة",
    passwordResetSuccess: "تم إعادة تعيين كلمة المرور بنجاح.",
    passwordResetFailed: "فشل إعادة تعيين كلمة المرور. يرجى المحاولة مرة أخرى.",
    confirmPassward: "تأكيد كلمة المرور",
    resetPasswordButton: "إعادة تعيين كلمة المرور",
    resetPasswordCodeSent: "تم إرسال رمز التحقق إلى بريدك الإلكتروني.",
    passwordResetSuccessDescription: "يمكنك الآن تسجيل الدخول باستخدام كلمة المرور الجديدة.",
    barriers: "حواجز الصمود",
    barriersDescription: "تعرف على تأثير الحواجز في فلسطين",
    explore: "استكشف",
    userName: "المستخدم",
    newRide: "رحلة جديدة",
    suggestedRides: "رحلات مقترحة",
    createRide: "إنشاء رحلة",
    logout: "تسجيل الخروج",
    currentLocation: "الموقع الحالي",
    becomeDriver: "كن سائقًا",
    earnMoney: "اربح المال من خلال تقديم الرحلات",
    register: "تسجيل",
    searchPlaceholder: "ابحث عن وجهتك",
    searchError: "لم يتم العثور على نتائج",
    registerDriver: "تسجيل كسائق",
    carType: "نوع السيارة",
    carTypePlaceholder: "مثال: تويوتا كورولا",
    carSeats: "عدد المقاعد",
    carSeatsPlaceholder: "مثال: 4",
    uploadCarImage: "صورة السيارة",
    selectCarImage: "اضغط لاختيار صورة للسيارة",
    uploadProfileImage: "صورة البروفايل",
    selectProfileImage: "اضغط لاختيار صورة للبروفايل",
    registerDriverButton: "التسجيل كـ سائق",
    registering: "جاري التسجيل...",
    checkingData: "جاري التحقق من بياناتك...",
    pleaseWait: "برجاء الانتظار قليلاً أثناء التحقق من حالة حسابك كسائق",
    alert: "تنبيه",
    pendingDriverRequest: "لديك طلب قيد المراجعة. يرجى الانتظار حتى يتم مراجعة طلبك من قبل الإدارة.",
    rejectedDriverRequest: "تم رفض طلبك السابق للأسباب التالية:",
    noReasonSpecified: "لم يتم تحديد السبب",
    editAndResubmit: "يمكنك تعديل بياناتك وإعادة التقديم.",
    mediaPermissionRequired: "يجب منح صلاحيات الوصول إلى المعرض",
    driverStatusCheckError: "حدث خطأ أثناء التحقق من حالة السائق",
    invalidImageFormat: "يجب اختيار صورة بصيغة JPG أو PNG",
    imageSizeLimit: "حجم الصورة يجب أن يكون أقل من 5MB",
    imagePickError: "حدث خطأ أثناء اختيار الصورة",
    invalidCarSeats: "عدد المقاعد يجب أن يكون بين 1 و 10",
    imageUploadFailed: "فشل في تحميل الصور، يرجى المحاولة لاحقًا",
    newDriverRequestTitle: "طلب جديد للتسجيل كسائق",
    newDriverRequestMessage: "طلب جديد من {userName} للتسجيل كسائق",
    driverRequestSuccess: "تم تقديم طلب التسجيل كسائق بنجاح. سيتم مراجعة طلبك من قبل الإدارة",
    registrationError: "حدث خطأ أثناء التسجيل",
    ok: "حسناً",
    userNotAuthenticated: 'المستخدم غير مصادق',
    failedToLoadRides: 'فشل تحميل الرحلات. حاول مجددًا.',
    ended: 'منتهية',
    pending: 'قيد الانتظار',
    available: 'متاحة',
    from: 'من',
    to: 'إلى',
    user: "المستخدم",

    seats: 'مقاعد',
    retry: 'أعد المحاولة',
    noRidesAvailable: 'لا توجد رحلات متاحة',
    Home: 'الرئيسية',
    Rides: 'الرحلات',
    Chat: 'المحادثة',
    Barrier: 'الحواجز',
    Profile: 'الحساب',
    Settings: 'الإعدادات',
    Help: 'المساعدة',
    Logout: 'تسجيل الخروج',
    Notifications: 'الإشعارات',
    Language: 'اللغة',
    Theme: 'الثيم',
    About: 'عن التطبيق',
    Terms: 'الشروط والأحكام',
    Privacy: 'الخصوصية',
    Contact: 'التواصل',
    Feedback: 'التغذية الرجعية',
    Rate: 'تقييم التطبيق',
    Share: 'مشاركة التطبيق',
    april: 'أبريل',
    may: 'مايو',
    june: 'يونيو',
    july: 'يوليو',
    august: 'أغسطس',
    september: 'سبتمبر',
    october: 'أكتوبر',
    november: 'نوفمبر',
    december: 'ديسمبر',
    january: 'يناير',
    february: 'فبراير',
    march: 'مارس',
    DriverInformation: 'معلومات السائق',
    CarType: 'نوع السيارة',
    NumberOfSeats: 'عدد المقاعد',
    DriverStatus: 'حالة السائق',
    RegistrationDate: 'تاريخ التسجيل',
    CarImage: 'صورة السيارة',
    AccountInformation: 'معلومات الحساب',
    PhoneNumber: 'رقم الهاتف',
    MemberSince: 'منذ',
    Active: 'نشط',
    Inactive: 'غير نشط',
    TotalRides: 'إجمالي الرحلات',
    Rating: 'التقييم',
    BecomeDriver: 'كن سائقًا',
    EarnMoney: 'اربح المال من خلال تقديم الرحلات',
    AdminDashboard: 'لوحة التحكم الإدارية',
    DriverApplications: 'طلبات التسجيل كسائق',
    ManageDriverRequests: 'إدارة طلبات التسجيل كسائق',
    Nablus: 'نابلس',
    Hebron: 'الخليل',
    Ramallah: 'رام الله',
    Jerusalem: 'القدس',
    Bethlehem: 'بيت لحم',
    Jenin: 'جنين',
    Tulkarm: 'طولكرم',
    Qalqilya: 'قلقيلية',
    Salfit: 'سلفيت',
    Tubas: 'طوباس',
    editProfile: "تعديل الملف الشخصي",
    language: "اللغة",
    notifications: "الإشعارات",
    location: "الموقع",
    support: "الدعم",
    shareApp: "مشاركة التطبيق",
    shareAppMessage: "تحقق من تطبيق وسيلني - تطبيق مشاركة الرحلات!",
    rateUs: "قيم التطبيق",
    privacyPolicy: "سياسة الخصوصية",
    helpAndSupport: "المساعدة والدعم",
    account: "الحساب",
    edit: "تعديل",
    delete: "حذف",
    deleteAccount: "حذف الحساب",
    deleteAccountDescription: "تأكيد حذف الحساب",
    trackRide: "تتبع الرحلة",
    driver: "السائق",
    inProgress: "قيد التنفيذ",
    completed: "مكتملة",
    contactDriver: "تواصل مع السائق",
    emergencyContact: "اتصال طوارئ",
    emergencyContactDescription: "هل أنت متأكد من أنك تريد الاتصال بالطوارئ؟",
    callEmergency: "اتصال بالطوارئ",
    rideInProgress: "الرحلة جارية بشكل طبيعي",
    rideDelayed: "تأخير في الرحلة",
    rideAlert: "تنبيه: لم يتم تحديث موقع الرحلة",
    estimatedArrival: "الوصول المتوقع",
    setParentEmail: "إضافة بريد الوالدين",
    parentEmailPlaceholder: "أدخل بريد الوالدين",
    saveParentEmail: "حفظ البريد",
    parentEmailSet: "تم حفظ بريد الوالدين بنجاح",
    parentEmailError: "حدث خطأ أثناء حفظ بريد الوالدين",
    checkIn: "تسجيل الوصول",
    checkOut: "تسجيل المغادرة",
    checkInSuccess: "تم تسجيل الوصول بنجاح",
    checkInError: "حدث خطأ أثناء تسجيل الوصول",
    checkOutSuccess: "تم تسجيل المغادرة بنجاح",
    checkOutError: "حدث خطأ أثناء تسجيل المغادرة",
    upcoming: "القادمة",
    past: "السابقة",
    all: "الكل",
    allRides: "كل الرحلات",
    myRides: "رحلاتي",
    registeredRides: "رحلات مسجلة",
    cancelled: "ملغي",
    noUpcomingRides: "لا توجد رحلات قادمة",
    noPastRides: "لا توجد رحلات سابقة",
    upcomingRidesWillAppearHere: "ستظهر رحلاتك القادمة هنا",
    pastRidesWillAppearHere: "ستظهر رحلاتك السابقة هنا",
    ridesYouDrove: "الرحلات التي قمت بقيادتها",
    ridesYouJoined: "الرحلات التي انضممت إليها",
    recurringTrip: "رحلة متكررة",
    availableSeats: "مقاعد متاحة",
    youAreTheDriver: "أنت السائق",
    theDriver: "السائق",
    daysNotSpecified: "الأيام غير محددة",
    stop: "نقطة توقف",
  },
  en: {
    chooseLanguage: "Choose Language",
    next: "Next",
    skip: "Skip",
    getStarted: "Get Started",
    CreateAcc: "Create Account",
    Search: "Search",
    searchDrivers: "Search Drivers",
    onboarding: [
      {
        title: "Travel smart, save time with Wasselny!",
        description: "Find people sharing your destination and enjoy comfortable trips at lower costs."
      },
      {
        title: "Be a Driver and Help Others!",
        description: "If you have an empty seat, don't ride alone! Share your trip and help people while reducing travel costs."
      },
      {
        title: "Ready to Go?",
        description: 'Join the smart mobility community now! Tap "Get Started" and create your account to find your first ride!'
      }
    ],
    signUp: "Create Your Account",
    phoneNumber: "Phone Number",
    fullName: "Full Name",
    enterYourName: "Enter your name",
    email: "Email",
    password: "Password",
    gender: "Gender",
    selectGender: "Select Gender",
    workIndustry: "Work Industry",
    selectIndustry: "Select Industry",
    agreeToTerms: "I agree to the terms and conditions",
    cancel: "Cancel",
    genders: ['Male', 'Female'],
    industries: [
      'Student',
      'Employee',
      'Freelancer',
      'Engineer',
      'Doctor',
      'Teacher',
      'Accountant',
      'Software Developer',
      'Merchant',
      'Healthcare Worker',
    ],
    explore: "Explore",
    user: "User",

    other: "Other",
    login: "Login",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account?",
    agreeToTermsAlert: "Please agree to the terms and conditions",
    signUpButton: "Sign Up",
    alreadyHaveAccount: "Already have an account?",
    logIn: "Log In",
    verificationSent: "We've sent a verification code to",
    code: "Code",
    verifyEmail: "Verify Email",
    verified: "Verified",
    verificationSuccess: "You have successfully verified your account.",
    browseHome: "Browse Home",
    error: "Error",
    fillAllFields: "Please fill all fields.",
    verificationFailed: "Verification failed. Please try again.",
    SendVCode: "We've sent a verification code to",
    Verification: "Verification",
    Code: "Code",
    VerifyEmail: "Verify Email",
    signInFailed: "Sign in failed. Please try again.",
    welcome: "Welcome!",
    forgotPasswordDescription: "Enter your email to receive a password reset link.",
    sendResetLink: "Send Reset Link",
    backToSignIn: "Back to Sign In",
    fillEmailField: "Please enter your email.",
    resetPasswordLinkSent: "A password reset link has been sent to your email.",
    success: "Success",
    resetPassword: "Reset Password",
    resetPasswordDescription: "Enter the verification code you received via email and your new password.",
    verificationCode: "Verification Code",
    newPassword: "New Password",
    resetPasswordButton: "Reset Password",
    confirmPassward: "Confirm Password",
    passwordResetSuccess: "Password reset successfully.",
    passwordResetFailed: "Failed to reset password. Please try again.",
    resetPasswordCodeSent: "A verification code has been sent to your email.",
    passwordResetSuccessDescription: "You can now log in using your new password.",
    logout: "Logout",
    barriers: "Barriers",
    barriersDescription: "Learn about the impact of checkpoints in Palestine",
    userName: "User",
    
    newRide: "New Ride",
    suggestedRides: "Suggested Rides",
    createRide: "Create Ride",
    currentLocation: "Current Location",
    becomeDriver: "Become a Driver",
    earnMoney: "Earn money by providing rides",
        register: "Register",
    searchPlaceholder: "Search destination",
    searchError: "No results found",
    registerDriver: "Register as Driver",
    carType: "Car Type",
    carTypePlaceholder: "Example: Toyota Corolla",
    carSeats: "Number of Seats",
    carSeatsPlaceholder: "Example: 4",
    uploadCarImage: "Car Image",
    selectCarImage: "Press to select car image",
    uploadProfileImage: "Profile Image",
    selectProfileImage: "Press to select profile image",
    registerDriverButton: "Register as Driver",
    registering: "Registering...",
    checkingData: "Checking your data...",
    pleaseWait: "Please wait while we verify your driver account status",
    alert: "Alert",
    pendingDriverRequest: "You have a pending driver request. Please wait until it is reviewed by the administration.",
    rejectedDriverRequest: "Your previous driver request was rejected for the following reasons:",
    noReasonSpecified: "No reason specified",
    editAndResubmit: "You can edit your information and resubmit.",
    mediaPermissionRequired: "Media access permission is required",
    driverStatusCheckError: "An error occurred while checking driver status",
    invalidImageFormat: "Please select an image in JPG or PNG format",
    imageSizeLimit: "Image size must be less than 5MB",
    imagePickError: "An error occurred while selecting the image",
    invalidCarSeats: "Number of seats must be between 1 and 10",
    imageUploadFailed: "Failed to upload images, please try again later",
    newDriverRequestTitle: "New Driver Registration Request",
    newDriverRequestMessage: "New driver registration request from {userName}",
    driverRequestSuccess: "Driver registration request submitted successfully. It will be reviewed by the administration.",
    registrationError: "An error occurred during registration",
    ok: "OK",
    userNotAuthenticated: 'User not authenticated',
    failedToLoadRides: 'Failed to load rides. Please try again.',
    ended: 'Ended',
    pending: 'Pending',
    available: 'Available',
    from: 'From',
    to: 'To',
    seats: 'seats',
    retry: 'Retry',
    noRidesAvailable: 'No rides available',
    Home: 'Home',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',
    january: 'January',
    february: 'February',
    march: 'March',
    findRide: 'Find a Ride',
findNow: 'Find Now',
    selectBothLocations: 'Please select both origin and destination locations',
    confirmRide: 'Confirm Ride',
    matchingRides: 'Matching Rides',
    currency: 'SAR', 
    ride: 'Ride',
    price: 'Price',
departureTime: 'Departure Time',
filter: 'Filter',
selectRide: 'Select Ride',
noSmoking: 'No Smoking',
noMusic: 'No Music',
noChildren: 'No Children',
sortByTime: 'Sort by Time',
sortByPrice: 'Sort by Price',
sortByRating: 'Sort by Rating',
editProfile: "Edit Profile",
    language: "Language",
    notifications: "Notifications",
    location: "Location",
    support: "Support",
    shareApp: "Share App",
    shareAppMessage: "Check out Wasselny - Your Carpooling App!",
    rateUs: "Rate Us",
    privacyPolicy: "Privacy Policy",
    helpAndSupport: "Help & Support",
    account: "Account",
    edit: "Edit",
    delete: "Delete",
    deleteAccount: "Delete Account",
    deleteAccountDescription: "Confirm Delete Account",
    Rides: 'Rides',

    Chat: 'Chat',

    Barrier: 'Barriers',

    Profile: 'Profile',

    Settings: 'Settings',

    Help: 'Help',

    Logout: 'Logout',

    Notifications: 'Notifications',

    Language: 'Language',

    Theme: 'Theme',

    About: 'About',

    Terms: 'Terms',

    Privacy: 'Privacy',

    Contact: 'Contact',

    Feedback: 'Feedback',

    Rate: 'Rate App',

    Share: 'Share App',

    DriverInformation: "Driver Information",

    CarType: "Car Type",

    NumberOfSeats: "Number of Seats",

    DriverStatus: "Driver Status",

    RegistrationDate: "Registration Date",

    CarImage: "Car Image",

    AccountInformation: "Account Information",

    PhoneNumber: "Phone Number",

    MemberSince: "Member Since",

    Active: "Active",

    Inactive: "Inactive",

    TotalRides: "Total Rides",

    Rating: "Rating",

    BecomeDriver: "Become a Driver",

    EarnMoney: "Earn money by providing rides",

    AdminDashboard: "Admin Dashboard",

    DriverApplications: "Driver Applications",

    ManageDriverRequests: "Manage Driver Registration Requests",

    Nablus: "Nablus",

    Hebron: "Hebron",

    Ramallah: "Ramallah",

    Jerusalem: "Jerusalem",

    Bethlehem: "Bethlehem",

    Jenin: "Jenin",

    Tulkarm: "Tulkarm",

    Qalqilya: "Qalqilya",

    Salfit: "Salfit",

    Tubas: "Tubas",

    trackRide: "Track Ride",
    driver: "Driver",
    inProgress: "In Progress",
    completed: "Completed",
    contactDriver: "Contact Driver",
    emergencyContact: "Emergency Contact",
    emergencyContactDescription: "Are you sure you want to make an emergency call?",
    callEmergency: "Call Emergency",
    rideInProgress: "Ride is proceeding normally",
    rideDelayed: "Ride is delayed",
    rideAlert: "Alert: Ride location not updated",
    estimatedArrival: "Estimated Arrival",
    setParentEmail: "Add Parent Email",
    parentEmailPlaceholder: "Enter parent's email",
    saveParentEmail: "Save Email",
    parentEmailSet: "Parent email saved successfully",
    parentEmailError: "Error saving parent email",
    checkIn: "Check In",
    checkOut: "Check Out",
    checkInSuccess: "Successfully checked in",
    checkInError: "Error checking in",
    checkOutSuccess: "Successfully checked out",
    checkOutError: "Error checking out",
    upcoming: "Upcoming",
    past: "Past",
    all: "All",
    allRides: "All Rides",
    myRides: "My Rides",
    registeredRides: "Registered Rides",
    cancelled: "Cancelled",
    noUpcomingRides: "No Upcoming Rides",
    noPastRides: "No Past Rides",
    upcomingRidesWillAppearHere: "Your upcoming rides will appear here",
    pastRidesWillAppearHere: "Your past rides will appear here",
    ridesYouDrove: "Rides You Drove",
    ridesYouJoined: "Rides You Joined",
    recurringTrip: "Recurring Trip",
    availableSeats: "available seats",
    youAreTheDriver: "You are the driver",
    theDriver: "Driver",
    daysNotSpecified: "Days not specified",
    stop: "Stop",
  },
};